### ISSUE TITLE
Does not work with Go version 1.15

### ISSUE THREAD

**Issue by cruxic** [judwhite/go-svc#12]
go-svc has been working great for me. However, after upgrading from Go 1.14.1 to 1.15.0 my Windows 10 service no longer works! When I attempt to start the service, Windows gives this error:

```
Error 1067: The process terminated unexpectedly
```

The Go 1.15 release notes talk about significant changes to the Linker, perhaps that's the problem? The issue is easy to reproduce using the Example program from the go-svc readme.  Windows 10 Professional, build 1903.

**Comment by judwhite** [comment]
@cruxic It works with the latest version of `go-svc`. Can you test on your end?

**Comment by cruxic** [comment]
I confirm it works now. Thanks!
