### ISSUE TITLE
Programatic graceful stop?

### ISSUE THREAD

**Issue by gridmon** [judwhite/go-svc#3]
I've written a client for win/lin/mac that can run interactively, or as a service, or as a scheduled task.
Whilst using go-svc handles a graceful stop when a SIGINT or windows service stop is received, I want to also be able to call prg.Stop() to stop programatically eg after a set number of interactions/time etc.

For some calling prg.Stop() (as per your example/main.go) just hangs.
I've also tried sending a SIGINT to self: This works on mac/lin causing the Stop() func to run, but on windows it exits immediately without calling Stop()

How do you stop go-svc programatically (at the moment I'm just doing os.exit() but that seems crude).

**Comment by judwhite** [comment]
If you call `prg.Stop()` then `os.Exit` it's not very nice looking but it'll get the job done.

I can add a `svc.Shutdown()` function to tear down the service and call `prg.Stop()`. If you're running it as a Windows service it may see this as a failure, and if you have any failure actions setup it might try to restart the service. I'll test this scenario.

**Comment by judwhite** [comment]
@gridmon This should be addressed with the addition of the `Context` interface
