### ISSUE TITLE
Calling  p.svr.stop() from within Stop()

### ISSUE THREAD

**Issue by gridmon** [judwhite/go-svc#4]
I notice that lines 67-69 in https://github.com/judwhite/go-svc/blob/master/example/main.go:
	if err := p.svr.stop(); err != nil {
		return err
	}
make a point of calling stop, whereas the example Stop function in the readme does not .

Could you please clarify if calling p.svr.stop is necessary?

**Comment by judwhite** [comment]
Hi @gridmon 

`p.svr.stop()` calls [func (s *server) stop()](https://github.com/judwhite/go-svc/blob/master/example/server.go#L25) which tells the `server` instance to do its graceful shutdown. After [`func (p program) Stop()`](https://github.com/judwhite/go-svc/blob/master/example/main.go#L65) returns the process exits.

In the example, the `program` class is kind of a wrapper which listens for control events, and `server` might be an HTTP server or some other long-running instance doing work. The README is simpler and doesn't contain a `server`, it does all the work in one type.

It's not strictly necessary to do a clean shutdown, and as a general rule you shouldn't depend on it, but if possible clean shutdown is usually preferable. That said this particular piece isn't core to how the package works but it is a common pattern.

Does that help? I'm going to take a look at the other issue #3 now.
